### ISSUE TITLE
Error injecting: com.github.klieber.phantomjs.mojo.InstallPhantomJsMojo

### ISSUE THREAD

**Issue by krysalead** [klieber/phantomjs-maven-plugin#34]
Hi,

First of all, thanks for this plugin, it helps a lot !
I am using the version 0.7 (same with 0.6) of your plugin, using 

Apache Maven 3.0.4 (r1232337; 2012-01-17 09:44:56+0100)
Maven home: d:\java\apache-maven-3.0.4
Java version: 1.6.0_26, vendor: Sun Microsystems Inc.
Java home: d:\java\jdk1.6.0_26\jre
Default locale: en_IE, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"

The following exception is thrown.

28-May-2015 16:30:19 org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: com.github.klieber.phantomjs.mojo.InstallPhantomJsMojo
com.google.inject.ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in com.github.klieber.phantomjs.mojo.InstallPhantomJsMojo. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.github.klieber.phantomjs.mojo.InstallPhantomJsMojo.class(Unknown Source)
  while locating com.github.klieber.phantomjs.mojo.InstallPhantomJsMojo

1 error
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:991)
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:950)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1000)
        at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)

If you need anything else to help

**Comment by jhovell** [comment]
this plugin is awesome! Love the way you have packaged up Phantom binaries as maven artifacts. Works great on my OSX laptop. Went to run it on my Linux Jenkins server and get the exact same stack trace.

This is on JDK8 / Maven 3.2 / Ubuntu Linux.  Thanks for any help!

**Comment by klieber** [comment]
@krysalead or @jhovell can you please send my the maven pom config you are using?

**Comment by jhovell** [comment]
@klieber sure I'll try to put a simplified one together. However, as I mentioned it worked perfectly on my Mac with the following maven. It failed on our Ubuntu Linux CI server (which I don't have access to) so I might suspect the problem has to do with the maven version and not the pom. I might be able to reproduce with your example POM for example.

mvn --version (works great)
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 08:22:22-0700)
Maven home: /usr/local/Cellar/maven/3.1.1/libexec
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.5", arch: "x86_64", family: "mac"

I'll post up the Linux version + example POM as soon as I can put it together

**Comment by jhovell** [comment]
From Linux (where I get the error)
mvn --version

Apache Maven 3.0.4
Maven home: /usr/share/maven
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.2.0-77-virtual", arch: "amd64", family: "unix"

Maybe the problem is with maven 3.0.4 / 3.0.x?

**Comment by jhovell** [comment]
@klieber For me, upgrading to Apache Maven 3.1 fixes the problem. Maybe there is some dependency convergence problem with plexus/guice?

**Comment by klieber** [comment]
Sorry, I didn't read this issue close enough at first.  @jhovell, you are right the plugin requires Maven 3.1 or higher.

**Comment by dougmorato** [comment]
Hello,

I have the same issue using maven 3.3.3 (installed from homebrew) on mac.

No idea on how to fix. Any suggestions ?

```Shell
[INFO] --- phantomjs-maven-plugin:0.7:install (default) @ webgoat-container ---
Aug 24, 2015 1:50:55 PM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: com.github.klieber.phantomjs.mojo.InstallPhantomJsMojo
com.google.inject.ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in com.github.klieber.phantomjs.mojo.InstallPhantomJsMojo. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.github.klieber.phantomjs.mojo.InstallPhantomJsMojo.class(Unknown Source)
  while locating com.github.klieber.phantomjs.mojo.InstallPhantomJsMojo

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:991)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:950)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1000)
	at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:965)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:961)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

```Shell
mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T07:57:37-04:00)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.8.0_51, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11", arch: "x86_64", family: "mac"
```


Here is the relevant entry in my pom
```XML
           <plugin>
                <groupId>com.github.klieber</groupId>
                <artifactId>phantomjs-maven-plugin</artifactId>
                <version>0.7</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>install</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <version>1.9.8</version>
                </configuration>
            </plugin>
...
        <dependency>
            <groupId>com.github.klieber</groupId>
            <artifactId>phantomjs-maven-plugin</artifactId>
            <version>0.7</version>
        </dependency>
```

**Comment by dougmorato** [comment]
Just to note that I also tried versions: 0.6, 0.5, 0.4

**Comment by marnix** [comment]
@klieber Could commit d7e6c56 from @hennr be merged?  That would have helped me-- I'm stuck on Maven 3.0.x for external reasons and it took me a long time to find out I could not use this plugin... :-(

Thanks!
