### ISSUE TITLE
Unable to download phantomjs artifact through company maven repository

### ISSUE THREAD

**Issue by reda-alaoui** [klieber/phantomjs-maven-plugin#48]
Hello,

We have a company maven repository that proxies all maven artifact requests.

It seems that phantomjs-maven-plugin tries to download phantomjs artifact in a way that is preventing our company repository from getting the artifact from maven central.

Maybe the issue lies in aether project or the way it is used?

```
Downloading: http://repo.mycompany.com/repository/all/com/github/klieber/phantomjs/1.9.8/phantomjs-1.9.8-linux-x86_64.tar.bz2
[ERROR] Unable to locate phantomjs binary
com.github.klieber.phantomjs.install.InstallationException: Unable to install phantomjs.
	at com.github.klieber.phantomjs.install.PhantomJsInstaller.install(PhantomJsInstaller.java:55)
	at com.github.klieber.phantomjs.locate.ArchiveLocator.locate(ArchiveLocator.java:45)
	at com.github.klieber.phantomjs.locate.CompositeLocator.locate(CompositeLocator.java:39)
	at com.github.klieber.phantomjs.locate.PhantomJsLocator.locate(PhantomJsLocator.java:58)
	at com.github.klieber.phantomjs.mojo.InstallPhantomJsMojo.run(InstallPhantomJsMojo.java:180)
	at com.github.klieber.phantomjs.mojo.AbstractPhantomJsMojo.execute(AbstractPhantomJsMojo.java:73)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.github.klieber.phantomjs.download.DownloadException: Unable to resolve artifact.
	at com.github.klieber.phantomjs.download.RepositoryDownloader.download(RepositoryDownloader.java:64)
	at com.github.klieber.phantomjs.install.PhantomJsInstaller.install(PhantomJsInstaller.java:52)
	... 18 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact com.github.klieber:phantomjs:tar.bz2:linux-x86_64:1.9.8 in company-repo-all (http://repo.mycompany.com/repository/all)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at com.github.klieber.phantomjs.download.RepositoryDownloader.download(RepositoryDownloader.java:58)
	... 19 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.github.klieber:phantomjs:tar.bz2:linux-x86_64:1.9.8 in company-repo-all (http://repo.mycompany.com/repository/all)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 23 more
```

Regards

**Comment by reda-alaoui** [comment]
I am closing this issue since we are using Archiva 1.3.9 as the company repo.
I think the issue is caused by https://issues.apache.org/jira/browse/MRM-739.
