### ISSUE TITLE
Error when running in child module

### ISSUE THREAD

**Issue by shawmanz32na** [klieber/phantomjs-maven-plugin#62]
We have a multi-module project in which we declare and configure the **phantomjs-maven-plugin** for optional use by the child modules. When the plugin is enabled for a child module and we run `mvn` from the child module's directory to build only that module, **phantomjs-maven-plugin** executes successfully. However, when `mvn` is run from the parent module's directory, the **phantomjs-maven-plugin** fails to execute for that same child module, giving the following error:

```
Failed to execute PhantomJS command: Unable to start phantomjs process. Cannot run program "cmd.exe" (in directory "test"): CreateProcess error=267, The directory name is invalid -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.klieber:phantomjs-maven-plugin:0.7:exec (default) on project CMS_Chat_Management_Portlet: Failed to execute PhantomJS command
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to execute PhantomJS command
        at com.github.klieber.phantomjs.mojo.ExecPhantomJsMojo.run(ExecPhantomJsMojo.java:139)
        at com.github.klieber.phantomjs.mojo.AbstractPhantomJsMojo.execute(AbstractPhantomJsMojo.java:73)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: com.github.klieber.phantomjs.exec.ExecutionException: Unable to start phantomjs process.
        at com.github.klieber.phantomjs.exec.PhantomJsProcessBuilder.start(PhantomJsProcessBuilder.java:104)
        at com.github.klieber.phantomjs.exec.PhantomJsExecutor.execute(PhantomJsExecutor.java:33)
        at com.github.klieber.phantomjs.mojo.ExecPhantomJsMojo.run(ExecPhantomJsMojo.java:134)
        ... 23 more
Caused by: java.io.IOException: Cannot run program "cmd.exe" (in directory "test"): CreateProcess error=267, The directory name is invalid
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at com.github.klieber.phantomjs.exec.PhantomJsProcessBuilder.start(PhantomJsProcessBuilder.java:102)
        ... 25 more
Caused by: java.io.IOException: CreateProcess error=267, The directory name is invalid
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:420)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:151)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 27 more
```

The parent pom can be simplified as follows:

```
...
      <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.github.klieber</groupId>
                    <artifactId>phantomjs-maven-plugin</artifactId>
                    <version>0.7</version>
                    <configuration>
                        <version>2.1.1</version>
                    </configuration>
                </plugin>
              </plugins>
            </pluginManagement>
          </build>
...
```

and the child pom as follows:

```
...
      <build>
        <plugins>
            <plugin>
                <groupId>com.github.klieber</groupId>
                <artifactId>phantomjs-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>install</goal>
                            <goal>exec</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <workingDirectory>test</workingDirectory>
                    <script>${basedir}/../test_lib/qunit-phantomjs-runner-2.3.1/runner-list.js</script>
                    <arguments>
                        <argument>test_suite.html</argument>
                        <argument>30</argument>
                    </arguments>
                </configuration>
            </plugin>
          </plugins>
        </build>
...
```

The debug information for the module execution when run from the parent directory is:

```
[INFO] --- phantomjs-maven-plugin:0.7:exec (default) @ CMS_Chat_Management_Portlet ---
[DEBUG] Configuring mojo com.github.klieber:phantomjs-maven-plugin:0.7:exec from plugin realm ClassRealm[plugin>com.github.klieber:phantomjs-maven-plugin:0.7, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5ef04b5]
[DEBUG] Configuring mojo 'com.github.klieber:phantomjs-maven-plugin:0.7:exec' with basic configurator -->
[DEBUG]   (f) arguments = [test_suite.html, 30]
[DEBUG]   (f) failOnNonZeroExitCode = true
[DEBUG]   (f) mavenProject = MavenProject: mil.mc2sa:CMS_Chat_Management_Portlet:1.0.0-SNAPSHOT @ C:\Users\Developer\Source\cms\CMS_Chat_Management_Portlet\pom.xml
[DEBUG]   (f) phantomJsBinary = C:\Users\Developer\Source\cms\CMS_Chat_Management_Portlet\target\phantomjs-maven-plugin\phantomjs-2.1.1-windows\bin\phantomjs.exe
[DEBUG]   (f) propertyName = phantomjs.binary
[DEBUG]   (f) script = C:\Users\Developer\Source\cms\CMS_Chat_Management_Portlet/../test_lib/qunit-phantomjs-runner-2.3.1/runner-list.js
[DEBUG]   (f) skip = false
[DEBUG]   (f) workingDirectory = test
[DEBUG] -- end configuration --
[INFO] Executing phantomjs command
[DEBUG] phantomjs command: [cmd.exe, /X, /C, "C:\Users\Developer\Source\cms\CMS_Chat_Management_Portlet\target\phantomjs-maven-plugin\phantomjs-2.1.1-windows\bin\phantomjs.exe C:\Users\Developer\Source\cms\CMS_Chat_Management_Portlet/../test_lib/qunit-phantomjs-runner-2.3.1/runner-list.js test_suite.html 30"]
```

and the debug information for the module execution when run from the child directory is:
```
[INFO] --- phantomjs-maven-plugin:0.7:exec (default) @ CMS_Chat_Management_Portlet ---
[DEBUG] Configuring mojo com.github.klieber:phantomjs-maven-plugin:0.7:exec from plugin realm ClassRealm[plugin>com.github.klieber:phantomjs-maven-plugin:0.7, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@5ef04b5]
[DEBUG] Configuring mojo 'com.github.klieber:phantomjs-maven-plugin:0.7:exec' with basic configurator -->
[DEBUG]   (f) arguments = [test_suite.html, 30]
[DEBUG]   (f) failOnNonZeroExitCode = true
[DEBUG]   (f) mavenProject = MavenProject: mil.mc2sa:CMS_Chat_Management_Portlet:1.0.0-SNAPSHOT @ C:\Users\Developer\Source\cms\CMS_Chat_Management_Portlet\pom.xml
[DEBUG]   (f) phantomJsBinary = C:\Users\Developer\Source\cms\CMS_Chat_Management_Portlet\target\phantomjs-maven-plugin\phantomjs-2.1.1-windows\bin\phantomjs.exe
[DEBUG]   (f) propertyName = phantomjs.binary
[DEBUG]   (f) script = C:\Users\Developer\Source\cms\CMS_Chat_Management_Portlet/../test_lib/qunit-phantomjs-runner-2.3.1/runner-list.js
[DEBUG]   (f) skip = false
[DEBUG]   (f) workingDirectory = test
[DEBUG] -- end configuration --
[INFO] Executing phantomjs command
[DEBUG] phantomjs command: [cmd.exe, /X, /C, "C:\Users\Developer\Source\cms\CMS_Chat_Management_Portlet\target\phantomjs-maven-plugin\phantomjs-2.1.1-windows\bin\phantomjs.exe C:\Users\Developer\Source\cms\CMS_Chat_Management_Portlet/../test_lib/qunit-phantomjs-runner-2.3.1/runner-list.js test_suite.html 30"]
```

**Comment by klieber** [comment]
This project is no longer being actively maintained.
